comments:
  UndocumentedPublicClass:
    active: true
    ignoreDefaultCompanionObject: true
  UndocumentedPublicFunction:
    active: true
coroutines:
  RedundantSuspendModifier:
    # too many false positives
    active: false
