name: Deploy release
on:
  release:
    types: [ published ]
jobs:
  docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            .gradle/configuration-cache
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK
        uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520 # v5.4.0
        with:
          distribution: temurin
          java-version: 21
      - name: Build jar
        run: ./gradlew assemble --no-daemon
      - name: Build vikunja-task-creator docker image
        run: |
          cd vikunja-task-creator
          TAG_NAME=${GITHUB_REF#"refs/tags/"}
          docker build -t vikunja-task-creator \
            --label="org.opencontainers.image.version=$TAG_NAME" \
            --label="org.opencontainers.image.revision=$GITHUB_SHA" \
            --label="org.opencontainers.image.created=$(date +'%Y-%m-%dT%H:%M:%S')" \
            .
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - name: Publish docker images
        run: |
          TAG_NAME=${GITHUB_REF#"refs/tags/"}
          # strip "v" prefix from tag name
          TAG_NAME=$(echo $TAG_NAME | sed -e 's/^v//')
          echo "Publishing image to ghcr.io/twinklehawk/vikunja-task-creator:$TAG_NAME"
          docker tag vikunja-task-creator ghcr.io/twinklehawk/vikunja-task-creator:$TAG_NAME
          docker tag vikunja-task-creator ghcr.io/twinklehawk/vikunja-task-creator:latest
          docker push ghcr.io/twinklehawk/vikunja-task-creator:$TAG_NAME
          docker push ghcr.io/twinklehawk/vikunja-task-creator:latest